### ISSUE TITLE
Running issue

### ISSUE THREAD

**Issue by michael3912** [chrisquinnr/Mettract#1]
I downloaded the project and install the node module and start by running meteor.But the project is not working?

**Comment by chrisquinnr** [comment]
Did you install the tesseract binary too? [https://github.com/tesseract-ocr/tesseract/wiki](https://github.com/tesseract-ocr/tesseract/wiki). What OS are you installing on? I've tested this on OSX and Ubuntu but no other OS.

**Comment by chrisquinnr** [comment]
Closing this for lack of response :)
